### ISSUE TITLE
New WPUF Dashboard responsive issue

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1130]
New WPUF Dashboard is showing the "Featured Image", only but not "Post Title", "Status", "Payment", "Options" columns of the table.

**How to reproduce:**

1) Create posts and visit your custom created dashboard with the shortcode `[wpuf_dashboard]` or `[wpuf_dashboard post_type="product"]`
2) You will see the above-mentioned `["Post Title", "Status", "Payment", "Options"]` columns will not be available with the responsive devices. 

**Screenshot/Screencast:**
Please [watch this video](https://drive.google.com/file/d/1M1aZr9eMd_bYiW9_tPUXGvNZ9gfwAXa3/view?usp=sharing) to know the output on different pixel/ratio.

**Comment by zamandevs** [comment]
Fixed on the release.

**Comment by mmarj** [comment]
@zamandevs Bhai, I think this issue doesn't resolve yet.

I have the **WPUF-V3.4.18** installed, but the output does not show as expected for the custom dashboard page.
- SS From Post Type custom Dashboard - https://prnt.sc/19aq6cp
- SS From Product Type custom Dashboard - https://prnt.sc/19arc0z

Would you please cross-check again? (CC- @FaraziF Bhai.)

**Comment by lukasj98** [comment]
I have the same problems with the newest version. Please fix it as soon as possible

**Comment by MaggiLulada** [comment]
The problem is still there. Users now cannot even see their posts. I hope you can very soon fix this, as post submission is a key element in my website. 
If I can support you in any way, let me know.

**Comment by lukasj98** [comment]
I have tested the new file and it looks awful￼￼
