### ISSUE TITLE
Fatal Error in Simple_Login.php: implode() Expects Array, String Given

### ISSUE THREAD

**Issue by 006rodaal** [weDevsOfficial/wp-user-frontend#1501]
Hello,

Since the new update from yesterday it's not possible to login anymore on the website. My logs show the following errors:
[15-Nov-2024 11:46:08 UTC] PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /home/[redacted-for-privacy-by-me]public_html/wp-content/plugins/wp-user-frontend/includes/Free/Simple_Login.php:514
Stack trace:
#0 /home/[redacted-for-privacy-by-me]public_html/wp-content/plugins/wp-user-frontend/includes/Free/Simple_Login.php(514): implode()
#1 /home/[redacted-for-privacy-by-me]public_html/wp-includes/class-wp-hook.php(324): WeDevs\Wpuf\Free\Simple_Login->process_login()
#2 /home/[redacted-for-privacy-by-me]public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /home/[redacted-for-privacy-by-me]public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/[redacted-for-privacy-by-me]public_html/wp-settings.php(704): do_action()
#5 /home/[redacted-for-privacy-by-me]public_html/wp-config.php(103): require_once('/home/deb145809...')
#6 /home/[redacted-for-privacy-by-me]public_html/wp-load.php(50): require_once('/home/deb145809...')
#7 /home/[redacted-for-privacy-by-me]public_html/wp-blog-header.php(13): require_once('/home/deb145809...')
#8 /home/[redacted-for-privacy-by-me]public_html/index.php(17): require('/home/deb145809...')
#9 {main}
  thrown in /home/[redacted-for-privacy-by-me]public_html/wp-content/plugins/wp-user-frontend/includes/Free/Simple_Login.php on line 514

Could you please solve this? Thanks!

**Comment by 006rodaal** [comment]
@sapayth could you please provide a quickfix?

**Comment by gossdhosting** [comment]
Waiting for a fix!!

**Comment by 006rodaal** [comment]
@gossdhosting i downloaded the 4.0.12 and uploaded this via ftp. Disabled auto updates and now waiting for the fix to upgrade 😓

**Comment by rebelojose** [comment]
solution by [smaggio](https://wordpress.org/support/users/slier/)

Same error. In Simple_Login.php on line 514 you try to concatenate an array when $errors is an empty string.
A temporary solution could be:

`$errors = implode( ‘, ‘, $errors );`
to
`if ( is_array( $errors ) ) {
$errors = implode( ‘, ‘, $errors );
}`

**Comment by anik-fahmid** [comment]
@006rodaal , @gossdhosting , and everyone following this thread,  
Thank you for your patience, and we're sorry for any inconvenience this issue has caused. We (@sapayth ) are actively working on a fix. Special thanks to @rebelojose  for suggesting the temporary solution.

In the meantime, we recommend rolling back to version `4.0.12` to maintain stability until the next release. We’ll keep you updated on our progress!

@saifislam01  is from our support team and will guide you with further help needed. 

Thank you all for your understanding.

**Comment by anik-fahmid** [comment]
Hi @006rodaal, @gossdhosting, and @rebelojose,

To resolve this quickly, we'd like to investigate the problem directly on your sites.

Could you please email your WordPress admin credentials and FTP access to me, anik@wedevs.com? If you're uncomfortable sharing your credentials, you can create a support ticket using this link: [[Support Ticket URL](https://wedevs.com/account/tickets/)].

Rest assured, any credentials shared with us will be treated with the utmost confidentiality and used strictly for debugging purposes. Once we've identified the root cause, we'll promptly work on a fix.

In the meantime, for a temporary workaround, rolling back to version 4.0.12 (as @006rodaal did) is a good option to avoid disruption.

I am looking forward to your response!

Best regards,
Fahmid from weDevs.

**Comment by gossdhosting** [comment]
The issue is still not resolved.

**Comment by Anower16** [comment]
Hi all @rebelojose, @gossdhosting, @006rodaal, @jweisman,

We are looking into this issue and working on a fix. Please stay with us. We will let you know the update shortly. This is added to the priority list. 

If you haven't contacted our technical support team please share your concern here. We might need your site access to apply the fix. 

Contact: https://wedevs.com/contact/

Thanks and have a nice day.

**Comment by anik-fahmid** [comment]
Hello all!

@rebelojose, @gossdhosting, @006rodaal, @jweisman,

We've released a fix in the latest version of the plugin, which addresses the login error you experienced. Please update to the latest version, and it should resolve the problem.

We appreciate your patience and understanding!

**Comment by andymnc** [comment]
> Hello all!
> 
> [@rebelojose](https://github.com/rebelojose), [@gossdhosting](https://github.com/gossdhosting), [@006rodaal](https://github.com/006rodaal), [@jweisman](https://github.com/jweisman),
> 
> We've released a fix in the latest version of the plugin, which addresses the login error you experienced. Please update to the latest version, and it should resolve the problem.
> 
> We appreciate your patience and understanding!

in my case, the 4.0.14 didn't solve the login problem introduced by the 4.0.13

**Comment by sapayth** [comment]
Hello @andymnc,

We're sorry to hear about the issue you're experiencing. Kindly create a [support](https://wedevs.com/contact/) ticket and provide your login credentials, so we can thoroughly investigate and resolve the problem on your site.
